#include "tests.h"

#if defined(HAVE_DRM_H) || defined(HAVE_DRM_DRM_H)

# include <errno.h>
# include <inttypes.h>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <sys/ioctl.h>

# ifdef HAVE_DRM_H
#  include <drm.h>
#  include <i915_drm.h>
# else
#  include <drm/drm.h>
#  include <drm/i915_drm.h>
# endif

# define TEST_NULL_ARG_EX(cmd, str)					\
	do {								\
		ioctl(-1, cmd, 0);					\
		printf("ioctl(-1, %s, NULL) = -1 EBADF (%m)\n", str);	\
	} while(0)

# define TEST_NULL_ARG(cmd) TEST_NULL_ARG_EX(cmd, #cmd)

int
main(void)
{
	TEST_NULL_ARG(DRM_IOCTL_I915_INIT);
	TEST_NULL_ARG(DRM_IOCTL_I915_FLUSH);
	TEST_NULL_ARG(DRM_IOCTL_I915_FLIP);
	TEST_NULL_ARG(DRM_IOCTL_I915_BATCHBUFFER);
	TEST_NULL_ARG(DRM_IOCTL_I915_IRQ_EMIT);
	TEST_NULL_ARG(DRM_IOCTL_I915_IRQ_WAIT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GETPARAM);
	TEST_NULL_ARG(DRM_IOCTL_I915_SETPARAM);
	TEST_NULL_ARG(DRM_IOCTL_I915_ALLOC);
	TEST_NULL_ARG(DRM_IOCTL_I915_FREE);
	TEST_NULL_ARG(DRM_IOCTL_I915_INIT_HEAP);
	TEST_NULL_ARG(DRM_IOCTL_I915_CMDBUFFER);
	TEST_NULL_ARG(DRM_IOCTL_I915_DESTROY_HEAP);
	TEST_NULL_ARG(DRM_IOCTL_I915_SET_VBLANK_PIPE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GET_VBLANK_PIPE);
	TEST_NULL_ARG(DRM_IOCTL_I915_VBLANK_SWAP);
	TEST_NULL_ARG(DRM_IOCTL_I915_HWS_ADDR);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_INIT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_EXECBUFFER);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_EXECBUFFER2);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_PIN);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_UNPIN);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_BUSY);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_SET_CACHING);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_GET_CACHING);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_THROTTLE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_ENTERVT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_LEAVEVT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_CREATE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_PREAD);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_PWRITE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_MMAP);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_MMAP_GTT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_SET_DOMAIN);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_SW_FINISH);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_SET_TILING);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_GET_TILING);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_GET_APERTURE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GET_PIPE_FROM_CRTC_ID);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_MADVISE);
	TEST_NULL_ARG(DRM_IOCTL_I915_OVERLAY_PUT_IMAGE);
	TEST_NULL_ARG(DRM_IOCTL_I915_OVERLAY_ATTRS);
	TEST_NULL_ARG(DRM_IOCTL_I915_SET_SPRITE_COLORKEY);
	TEST_NULL_ARG(DRM_IOCTL_I915_GET_SPRITE_COLORKEY);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_WAIT);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_CONTEXT_CREATE);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_CONTEXT_DESTROY);
	TEST_NULL_ARG(DRM_IOCTL_I915_REG_READ);
	TEST_NULL_ARG(DRM_IOCTL_I915_GET_RESET_STATS);
	TEST_NULL_ARG(DRM_IOCTL_I915_GEM_USERPTR);

	puts("+++ exited with 0 +++");
	return 0;
}
#else

SKIP_MAIN_UNDEFINED("HAVE_DRM_H && HAVE_DRM_DRM_H");

#endif
