/* Generated by ./xlat/gen.sh from ./xlat/drm_syncobj_handle_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_syncobj_handle_flags in mpers mode

# else

static const struct xlat_data drm_syncobj_handle_flags_xdata[] = {
#if defined(DRM_SYNCOBJ_FD_TO_HANDLE_FLAGS_IMPORT_SYNC_FILE) || (defined(HAVE_DECL_DRM_SYNCOBJ_FD_TO_HANDLE_FLAGS_IMPORT_SYNC_FILE) && HAVE_DECL_DRM_SYNCOBJ_FD_TO_HANDLE_FLAGS_IMPORT_SYNC_FILE)
  XLAT(DRM_SYNCOBJ_FD_TO_HANDLE_FLAGS_IMPORT_SYNC_FILE),
#endif
#if defined(DRM_SYNCOBJ_HANDLE_TO_FD_FLAGS_EXPORT_SYNC_FILE) || (defined(HAVE_DECL_DRM_SYNCOBJ_HANDLE_TO_FD_FLAGS_EXPORT_SYNC_FILE) && HAVE_DECL_DRM_SYNCOBJ_HANDLE_TO_FD_FLAGS_EXPORT_SYNC_FILE)
  XLAT(DRM_SYNCOBJ_HANDLE_TO_FD_FLAGS_EXPORT_SYNC_FILE),
#endif
};
static
const struct xlat drm_syncobj_handle_flags[1] = { {
 .data = drm_syncobj_handle_flags_xdata,
 .size = ARRAY_SIZE(drm_syncobj_handle_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
