/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_page_flip_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_page_flip_flags in mpers mode

# else

static const struct xlat_data drm_mode_page_flip_flags_xdata[] = {
#if defined(DRM_MODE_PAGE_FLIP_EVENT) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_EVENT) && HAVE_DECL_DRM_MODE_PAGE_FLIP_EVENT)
  XLAT(DRM_MODE_PAGE_FLIP_EVENT),
#endif
#if defined(DRM_MODE_PAGE_FLIP_ASYNC) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_ASYNC) && HAVE_DECL_DRM_MODE_PAGE_FLIP_ASYNC)
  XLAT(DRM_MODE_PAGE_FLIP_ASYNC),
#endif
#if defined(DRM_MODE_PAGE_FLIP_TARGET_ABSOLUTE) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET_ABSOLUTE) && HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET_ABSOLUTE)
  XLAT(DRM_MODE_PAGE_FLIP_TARGET_ABSOLUTE),
#endif
#if defined(DRM_MODE_PAGE_FLIP_TARGET_RELATIVE) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET_RELATIVE) && HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET_RELATIVE)
  XLAT(DRM_MODE_PAGE_FLIP_TARGET_RELATIVE),
#endif
#if defined(DRM_MODE_PAGE_FLIP_TARGET) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET) && HAVE_DECL_DRM_MODE_PAGE_FLIP_TARGET)
  XLAT(DRM_MODE_PAGE_FLIP_TARGET),
#endif
#if defined(DRM_MODE_PAGE_FLIP_FLAGS) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_FLAGS) && HAVE_DECL_DRM_MODE_PAGE_FLIP_FLAGS)
  XLAT(DRM_MODE_PAGE_FLIP_FLAGS),
#endif
};
static
const struct xlat drm_mode_page_flip_flags[1] = { {
 .data = drm_mode_page_flip_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_page_flip_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
