/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_set_plane_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_set_plane_flags in mpers mode

# else

static const struct xlat_data drm_mode_set_plane_flags_xdata[] = {
#if defined(DRM_MODE_PRESENT_TOP_FIELD) || (defined(HAVE_DECL_DRM_MODE_PRESENT_TOP_FIELD) && HAVE_DECL_DRM_MODE_PRESENT_TOP_FIELD)
  XLAT(DRM_MODE_PRESENT_TOP_FIELD),
#endif
#if defined(DRM_MODE_PRESENT_BOTTOM_FIELD) || (defined(HAVE_DECL_DRM_MODE_PRESENT_BOTTOM_FIELD) && HAVE_DECL_DRM_MODE_PRESENT_BOTTOM_FIELD)
  XLAT(DRM_MODE_PRESENT_BOTTOM_FIELD),
#endif
};
static
const struct xlat drm_mode_set_plane_flags[1] = { {
 .data = drm_mode_set_plane_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_set_plane_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
