/* Generated by ./xlat/gen.sh from ./xlat/drm_prime_handle_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_prime_handle_flags in mpers mode

# else

static const struct xlat_data drm_prime_handle_flags_xdata[] = {
#if defined(DRM_RDWR) || (defined(HAVE_DECL_DRM_RDWR) && HAVE_DECL_DRM_RDWR)
  XLAT(DRM_RDWR),
#endif
#if defined(DRM_CLOEXEC) || (defined(HAVE_DECL_DRM_CLOEXEC) && HAVE_DECL_DRM_CLOEXEC)
  XLAT(DRM_CLOEXEC),
#endif
};
static
const struct xlat drm_prime_handle_flags[1] = { {
 .data = drm_prime_handle_flags_xdata,
 .size = ARRAY_SIZE(drm_prime_handle_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
