/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_cursor_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_cursor_flags in mpers mode

# else

static const struct xlat_data drm_mode_cursor_flags_xdata[] = {
#if defined(DRM_MODE_CURSOR_BO) || (defined(HAVE_DECL_DRM_MODE_CURSOR_BO) && HAVE_DECL_DRM_MODE_CURSOR_BO)
  XLAT(DRM_MODE_CURSOR_BO),
#endif
#if defined(DRM_MODE_CURSOR_MOVE) || (defined(HAVE_DECL_DRM_MODE_CURSOR_MOVE) && HAVE_DECL_DRM_MODE_CURSOR_MOVE)
  XLAT(DRM_MODE_CURSOR_MOVE),
#endif
};
static
const struct xlat drm_mode_cursor_flags[1] = { {
 .data = drm_mode_cursor_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_cursor_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
