/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_atomic_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_atomic_flags in mpers mode

# else

static const struct xlat_data drm_mode_atomic_flags_xdata[] = {
#if defined(DRM_MODE_PAGE_FLIP_EVENT) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_EVENT) && HAVE_DECL_DRM_MODE_PAGE_FLIP_EVENT)
  XLAT(DRM_MODE_PAGE_FLIP_EVENT),
#endif
#if defined(DRM_MODE_PAGE_FLIP_ASYNC) || (defined(HAVE_DECL_DRM_MODE_PAGE_FLIP_ASYNC) && HAVE_DECL_DRM_MODE_PAGE_FLIP_ASYNC)
  XLAT(DRM_MODE_PAGE_FLIP_ASYNC),
#endif
#if defined(DRM_MODE_ATOMIC_TEST_ONLY) || (defined(HAVE_DECL_DRM_MODE_ATOMIC_TEST_ONLY) && HAVE_DECL_DRM_MODE_ATOMIC_TEST_ONLY)
  XLAT(DRM_MODE_ATOMIC_TEST_ONLY),
#endif
#if defined(DRM_MODE_ATOMIC_NONBLOCK) || (defined(HAVE_DECL_DRM_MODE_ATOMIC_NONBLOCK) && HAVE_DECL_DRM_MODE_ATOMIC_NONBLOCK)
  XLAT(DRM_MODE_ATOMIC_NONBLOCK),
#endif
#if defined(DRM_MODE_ATOMIC_ALLOW_MODESET) || (defined(HAVE_DECL_DRM_MODE_ATOMIC_ALLOW_MODESET) && HAVE_DECL_DRM_MODE_ATOMIC_ALLOW_MODESET)
  XLAT(DRM_MODE_ATOMIC_ALLOW_MODESET),
#endif
};
static
const struct xlat drm_mode_atomic_flags[1] = { {
 .data = drm_mode_atomic_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_atomic_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
