/* Generated by ./xlat/gen.sh from ./xlat/drm_modeset_cmd.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(_DRM_PRE_MODESET) || (defined(HAVE_DECL__DRM_PRE_MODESET) && HAVE_DECL__DRM_PRE_MODESET)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((_DRM_PRE_MODESET) == (1), "_DRM_PRE_MODESET != 1");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define _DRM_PRE_MODESET 1
#endif
#if defined(_DRM_POST_MODESET) || (defined(HAVE_DECL__DRM_POST_MODESET) && HAVE_DECL__DRM_POST_MODESET)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((_DRM_POST_MODESET) == (2), "_DRM_POST_MODESET != 2");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define _DRM_POST_MODESET 2
#endif

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_modeset_cmd in mpers mode

# else

static const struct xlat_data drm_modeset_cmd_xdata[] = {
 XLAT(_DRM_PRE_MODESET),
 XLAT(_DRM_POST_MODESET),
};
static
const struct xlat drm_modeset_cmd[1] = { {
 .data = drm_modeset_cmd_xdata,
 .size = ARRAY_SIZE(drm_modeset_cmd_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
