/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_fb_cmd2_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

extern const struct xlat drm_mode_fb_cmd2_flags[];

# else

static const struct xlat_data drm_mode_fb_cmd2_flags_xdata[] = {
#if defined(DRM_MODE_FB_INTERLACED) || (defined(HAVE_DECL_DRM_MODE_FB_INTERLACED) && HAVE_DECL_DRM_MODE_FB_INTERLACED)
  XLAT(DRM_MODE_FB_INTERLACED),
#endif
#if defined(DRM_MODE_FB_MODIFIERS) || (defined(HAVE_DECL_DRM_MODE_FB_MODIFIERS) && HAVE_DECL_DRM_MODE_FB_MODIFIERS)
  XLAT(DRM_MODE_FB_MODIFIERS),
#endif
};
#  if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
#  endif
const struct xlat drm_mode_fb_cmd2_flags[1] = { {
 .data = drm_mode_fb_cmd2_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_fb_cmd2_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
