/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_fb_dirty_cmd_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_fb_dirty_cmd_flags in mpers mode

# else

static const struct xlat_data drm_mode_fb_dirty_cmd_flags_xdata[] = {
#if defined(DRM_MODE_FB_DIRTY_ANNOTATE_COPY) || (defined(HAVE_DECL_DRM_MODE_FB_DIRTY_ANNOTATE_COPY) && HAVE_DECL_DRM_MODE_FB_DIRTY_ANNOTATE_COPY)
  XLAT(DRM_MODE_FB_DIRTY_ANNOTATE_COPY),
#endif
#if defined(DRM_MODE_FB_DIRTY_ANNOTATE_FILL) || (defined(HAVE_DECL_DRM_MODE_FB_DIRTY_ANNOTATE_FILL) && HAVE_DECL_DRM_MODE_FB_DIRTY_ANNOTATE_FILL)
  XLAT(DRM_MODE_FB_DIRTY_ANNOTATE_FILL),
#endif
};
static
const struct xlat drm_mode_fb_dirty_cmd_flags[1] = { {
 .data = drm_mode_fb_dirty_cmd_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_fb_dirty_cmd_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
