/* Generated by ./xlat/gen.sh from ./xlat/drm_mode_get_property_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_mode_get_property_flags in mpers mode

# else

static const struct xlat_data drm_mode_get_property_flags_xdata[] = {
#if defined(DRM_MODE_PROP_PENDING) || (defined(HAVE_DECL_DRM_MODE_PROP_PENDING) && HAVE_DECL_DRM_MODE_PROP_PENDING)
  XLAT(DRM_MODE_PROP_PENDING),
#endif
#if defined(DRM_MODE_PROP_RANGE) || (defined(HAVE_DECL_DRM_MODE_PROP_RANGE) && HAVE_DECL_DRM_MODE_PROP_RANGE)
  XLAT(DRM_MODE_PROP_RANGE),
#endif
#if defined(DRM_MODE_PROP_IMMUTABLE) || (defined(HAVE_DECL_DRM_MODE_PROP_IMMUTABLE) && HAVE_DECL_DRM_MODE_PROP_IMMUTABLE)
  XLAT(DRM_MODE_PROP_IMMUTABLE),
#endif
#if defined(DRM_MODE_PROP_ENUM) || (defined(HAVE_DECL_DRM_MODE_PROP_ENUM) && HAVE_DECL_DRM_MODE_PROP_ENUM)
  XLAT(DRM_MODE_PROP_ENUM),
#endif
#if defined(DRM_MODE_PROP_BLOB) || (defined(HAVE_DECL_DRM_MODE_PROP_BLOB) && HAVE_DECL_DRM_MODE_PROP_BLOB)
  XLAT(DRM_MODE_PROP_BLOB),
#endif
#if defined(DRM_MODE_PROP_BITMASK) || (defined(HAVE_DECL_DRM_MODE_PROP_BITMASK) && HAVE_DECL_DRM_MODE_PROP_BITMASK)
  XLAT(DRM_MODE_PROP_BITMASK),
#endif
#if defined(DRM_MODE_PROP_EXTENDED_TYPE) || (defined(HAVE_DECL_DRM_MODE_PROP_EXTENDED_TYPE) && HAVE_DECL_DRM_MODE_PROP_EXTENDED_TYPE)
  XLAT(DRM_MODE_PROP_EXTENDED_TYPE),
#endif
#if defined(DRM_MODE_PROP_ATOMIC) || (defined(HAVE_DECL_DRM_MODE_PROP_ATOMIC) && HAVE_DECL_DRM_MODE_PROP_ATOMIC)
  XLAT(DRM_MODE_PROP_ATOMIC),
#endif
};
static
const struct xlat drm_mode_get_property_flags[1] = { {
 .data = drm_mode_get_property_flags_xdata,
 .size = ARRAY_SIZE(drm_mode_get_property_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
