/* Generated by ./xlat/gen.sh from ./xlat/drm_syncobj_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(DRM_SYNCOBJ_CREATE_SIGNALED) || (defined(HAVE_DECL_DRM_SYNCOBJ_CREATE_SIGNALED) && HAVE_DECL_DRM_SYNCOBJ_CREATE_SIGNALED)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((DRM_SYNCOBJ_CREATE_SIGNALED) == ((1 << 0)), "DRM_SYNCOBJ_CREATE_SIGNALED != (1 << 0)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define DRM_SYNCOBJ_CREATE_SIGNALED (1 << 0)
#endif

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat drm_syncobj_flags in mpers mode

# else

static const struct xlat_data drm_syncobj_flags_xdata[] = {
 XLAT(DRM_SYNCOBJ_CREATE_SIGNALED),
};
static
const struct xlat drm_syncobj_flags[1] = { {
 .data = drm_syncobj_flags_xdata,
 .size = ARRAY_SIZE(drm_syncobj_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
